Worked on dashboard display
mtahir08/bootcamp_project_05 pull request #3
Opened 2020-03-07 10:42 UTC by khanrafay

- Created a dashboard in which all users are listed down.
- Created details dashboard page where specific user is shown as per id using useParam

2020-03-07 10:59 UTC, mtahir08 requested changes

2020-03-07 10:59 UTC, mtahir08 commented on src/Pages/Dashboard.js
> +                        <tr>
make it a separate component

2020-03-07 10:59 UTC, mtahir08 commented on src/Pages/Dashboard.js
> +            <tr key={user.id}>
make is separate component

2020-03-07 10:59 UTC, mtahir08 commented on src/Pages/Dashboard.js
> +    useEffect(() => {
make it with redux

2020-03-08 10:17 UTC, khanrafay commented on src/Pages/Dashboard.js
> +                        <tr>
Created it.

2020-03-08 10:17 UTC, khanrafay commented on src/Pages/Dashboard.js
> +    useEffect(() => {
Did it.

2020-03-08 10:17 UTC, khanrafay commented on src/Pages/Dashboard.js
> +            <tr key={user.id}>
Created...

2020-03-08 11:33 UTC, merged